Feat: Posting pictures and posts to the profile
CultureQuestORG/SDP2023 pull request #108
Opened 2023-04-23 18:05 UTC by lucamouchel

This PR allows users to post to their profiles when they are on the art description activity.

2023-04-25 14:09 UTC, hmiranda-queiros requested changes
Good work ! However, you need to wait for the PR on Firebase Storage refactor to be merged before merging this one because you created functions that were already implemented in other PRs, but lost in the codebase because no class was created for Storage before like it is the case for the Database.
I also put other small questions/comments and maybe we need to discuss with the rest of the team to decide in which way to go.

2023-04-29 07:25 UTC, lucamouchel commented on app/src/main/java/ch/epfl/culturequest/database/Database.java
> +        CompletableFuture<AtomicBoolean> future = new CompletableFuture<>();
to me we should update each independently, especially bc many fields will never be updated (ie only the score, username and profile pic can be changed i think)

2023-04-29 07:25 UTC, lucamouchel commented on app/src/main/java/ch/epfl/culturequest/ui/profile/ProfileFragment.java
> +        }
right above, `limit = postsAdded`

2023-04-30 13:03 UTC, hmiranda-queiros requested changes
Good changes, I just put a comment on something you may need to change because of work being done in the scan fragment.

2023-05-01 07:20 UTC, lucamouchel commented on app/src/main/java/ch/epfl/culturequest/ui/profile/ProfileFragment.java
> +        }
just bc the function retrieve posts uses attributes limit and offset, but it is useless yes

2023-05-01 09:42 UTC, hmiranda-queiros approved these changes
All good to merge !

2023-05-01 09:45 UTC, merged