feat: connect the account login with the profile page
CultureQuestORG/SDP2023 pull request #50
Opened 2023-03-21 13:13 UTC by alberttkt

With this PR the active user can see his own profile in the profile page.

2023-03-22 11:37 UTC, Th0h0 requested changes
I made some suggestions for changes regarding some specific elements. The rest looks good to me. I don't really know if you could achieve more test coverage given what your part is about.

2023-03-22 11:37 UTC, Th0h0 commented on app/src/main/java/ch/epfl/culturequest/ProfileCreatorActivity.java
Still about the `createProfile`method. If no image is selected, is it really required to still upload the default profile picture image to Firebase? Couldn't you just shortcut the process by uploading the default profile image only once to firebase, and then referencing it like that: `profile.setProfilePicture([default_image_url])`?

2023-03-22 11:37 UTC, Th0h0 commented on .idea/androidTestResultsUserPreferences.xml
Don't push that?

2023-03-22 11:37 UTC, Th0h0 commented on app/src/androidTest/java/ch/epfl/culturequest/ProfileCreatorActivityTest.java
>          Thread.sleep(2000);
I think you could use IdlingResources here instead.

2023-03-23 19:27 UTC, Th0h0 approved these changes
I don't see any more issues. It now looks good to me.

2023-03-23 19:41 UTC, Th0h0 commented on app/src/main/java/ch/epfl/culturequest/ProfileCreatorActivity.java
Wouldn't this change imply that an anonymous user who didn't choose a profile image, wouldn't have any profile picture set?

2023-03-23 23:11 UTC, TheGuyWithoutH commented on app/src/main/java/ch/epfl/culturequest/ProfileCreatorActivity.java
You are right, we should provide a default image for the users. I will give it to albert!

2023-03-23 23:15 UTC, TheGuyWithoutH reviewed
Just a few things to check in order to coordinate the database architecture, but seems fine otherwise.

2023-03-23 23:15 UTC, TheGuyWithoutH commented on app/src/main/java/ch/epfl/culturequest/database/Database.java
Why did you change this class? Isn't the `Database` class suppose to 'act' as a database, so need to implement this interface?

2023-03-23 23:15 UTC, TheGuyWithoutH commented on app/src/main/java/ch/epfl/culturequest/social/Profile.java
Are the images the scans of the user? Because in this case, it is maybe more relevant to wait once I finish the post classes to directly fetch the posts of the users rather than the pictures.

2023-03-24 01:17 UTC, Th0h0 commented on app/src/main/java/ch/epfl/culturequest/ProfileCreatorActivity.java
There currently is already a default image ([this one](https://firebasestorage.googleapis.com/v0/b/culturequest.appspot.com/o/profilePictures%2Fbasic_profile_picture.png?alt=media&token=8e407bd6-ad5f-401a-9b2d-7852ccfb9d62)), which is set when no image is selected by the user or the image upload fails.
I was pointing out the specific case of an anonymous user attempting to create a profile without selecting any image. In such a setup, no image would be set at all.

2023-03-24 09:09 UTC, alberttkt commented on app/src/main/java/ch/epfl/culturequest/ProfileCreatorActivity.java
Fixed!

2023-03-25 10:24 UTC, merged