hotfix in profile view model
CultureQuestORG/SDP2023 pull request #69
Opened 2023-03-29 18:10 UTC by lucamouchel

Fixes a problem when we searched for users it displayed the current user

2023-03-29 18:14 UTC, TheGuyWithoutH approved these changes
Good to go!

2023-03-29 18:15 UTC, alberttkt requested changes
Nice, just a comment

2023-03-29 18:18 UTC, lucamouchel commented on app/src/main/java/ch/epfl/culturequest/ui/profile/ProfileViewModel.java
> +        });
yes you're right, i rolled back to the previous code and just added a check

2023-03-29 18:21 UTC, alberttkt approved these changes
Nice!

2023-03-30 06:45 UTC, alberttkt requested changes

2023-03-30 06:45 UTC, alberttkt commented on app/src/main/java/ch/epfl/culturequest/ui/profile/ProfileViewModel.java
> +                });
why do you need to fetch the profile from the database if you already have selectedProfile?

2023-03-30 09:08 UTC, merged